jeans_mfg_data_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5433
      user: user
      password: password
      dbname: jeans_source_db

      # Base schema (will be overridden by dbt_project.yml + macro)
      schema: analytics

      threads: 1

    cloud:
      type: postgres
      host: ep-green-frog-alo9hq5t-pooler.c-3.eu-central-1.aws.neon.tech
      port: 5432
      user: neondb_owner
      password: npg_Qf9WicMD4SxP
      dbname: neondb
      schema: analytics
      threads: 1
      sslmode: require
