# dbt_project.yml

name: 'jeans_mfg_pipeline'
version: '1.0.0'
config-version: 2

profile: 'jeans_mfg_pipeline' # Ensure this matches your profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  jeans_mfg_pipeline:
    +materialized: view

    staging:
      +schema: staging
      +materialized: view

    marts:
       +schema: marts
       +materialized: table

sources:
  - name: raw_data
    database: airflow
    schema: public
    tables:
      - name: raw_orders
      - name: raw_bill_of_materials